var modules =
[
    [ "FIFO module documentation", "group___f_i_f_o__module.html", "group___f_i_f_o__module" ],
    [ "flash module documentation", "group__flash__module.html", "group__flash__module" ],
    [ "Frequencie module documentation", "group___frequencie__module.html", "group___frequencie__module" ],
    [ "FTM module documentation", "group___f_t_m__module.html", "group___f_t_m__module" ],
    [ "LEDs module documentation", "group___l_e_ds__module.html", "group___l_e_ds__module" ],
    [ "main module documentation", "group__main__module.html", "group__main__module" ],
    [ "Output module documentation", "group___output__module.html", "group___output__module" ],
    [ "packet module documentation", "group__packet__module.html", "group__packet__module" ],
    [ "PIT module documentation", "group___p_i_t__module.html", "group___p_i_t__module" ],
    [ "Regulation module documentation", "group___regulation__module.html", "group___regulation__module" ],
    [ "Requirements module documentation", "group___requirements__module.html", "group___requirements__module" ],
    [ "RTC module documentation", "group___r_t_c__module.html", "group___r_t_c__module" ],
    [ "SCP module documentation", "group___s_c_p__module.html", "group___s_c_p__module" ],
    [ "UART module documentation", "group___u_a_r_t__module.html", "group___u_a_r_t__module" ],
    [ "Cpu module documentation", "group___cpu__module.html", "group___cpu__module" ],
    [ "PE_Const module documentation", "group___p_e___const__module.html", "group___p_e___const__module" ],
    [ "PE_Error module documentation", "group___p_e___error__module.html", "group___p_e___error__module" ],
    [ "PE_Types module documentation", "group___p_e___types__module.html", "group___p_e___types__module" ],
    [ "Vectors module documentation", "group___vectors__module.html", null ],
    [ "Interrupt vector numbers", "group___interrupt__vector__numbers.html", "group___interrupt__vector__numbers" ],
    [ "Peripheral type defines", "group___peripheral__defines.html", "group___peripheral__defines" ],
    [ "Backward Compatibility", "group___backward___compatibility___symbols.html", null ]
];